export default {
    'china':[
        {name:'北京',pname:'beijing',value:0},
        {name:'天津',pname:'tianjin',value:0},
        {name:'河北',pname:'hebei',value:0},
        {name:'山西',pname:'shanxi',value:0},
        {name:'内蒙古',pname:'neimenggu',value:0},
        {name:'辽宁',pname:'liaoning',value:0},
        {name:'吉林',pname:'jilin',value:0},
        {name:'黑龙江',pname:'heilongjiang',value:0},
        {name:'上海',pname:'shanghai',value:0},
        {name:'江苏',pname:'jiangsu',value:0},
        {name:'浙江',pname:'zhejiang',value:0},
        {name:'安徽',pname:'anhui',value:0},
        {name:'福建',pname:'fujian',value:0},
        {name:'江西',pname:'zhejiang',value:0},
        {name:'山东',pname:'shandong',value:0},
        {name:'河南',pname:'henan',value:0},
        {name:'湖北',pname:'hubei',value:0},
        {name:'湖南',pname:'hunan',value:0},
        {name:'四川',pname:'sichuan',value:0},
        {name:'贵州',pname:'guizhou',value:0},
        {name:'云南',pname:'yunnan',value:0},
        {name:'西藏',pname:'xizang',value:0},
        {name:'陕西',pname:'shanxi1',value:0},
        {name:'甘肃',pname:'gansu',value:0},
        {name:'青海',pname:'qinghai',value:0},
        {name:'宁夏',pname:'ningxia',value:0},
        {name:'重庆市',pname:'chongqing',value:0},
        {name:'新疆',pname:'xinjiang',value:0},
        {name:'广东',pname:'guangdong',value:0},
        {name:'广西',pname:'guangxi',value:0},
        {name:'海南',pname:'hainan',value:0},
        {name:'台湾',pname:'taiwan',value:0},
        {name:'香港',pname:'xianggang',value:0},
        {name:'澳门',pname:'aomen',value:0},
    ],
    'shandong': [
        {name:'潍坊市',pname:'weifang',value:0},
        {name:'烟台市',pname:'yantai',value:0},
        {name:'临沂市',pname:'linyi',value:0},
        {name:'青岛市',pname:'qingdao',value:0},
        {name:'菏泽市',pname:'heze',value:0},
        {name:'济宁市',pname:'jining',value:0},
        {name:'德州市',pname:'dezhou',value:0},
        {name:'滨州市',pname:'binzhou',value:0},
        {name:'聊城市',pname:'liaocheng',value:0},
        {name:'东营市',pname:'dongying',value:0},
        {name:'济南市',pname:'jinan',value:0},
        {name:'泰安市',pname:'taian',value:0},
        {name:'威海市',pname:'weihai',value:0},
        {name:'日照市',pname:'rizhao',value:0},
        {name:'淄博市',pname:'zibo',value:0},
        {name:'枣庄市',pname:'zaozhuang',value:0},
        {name:'莱芜市',pname:'laiwu',value:0},
        {name:'章丘市',pname:'zhangqiu',value:0},
        {name:'东营市',pname:'dongyin',value:0},
    ],
    'weifang': [
        {name: "青州市", value: 0},
        {name: "奎文区", value: 0},
        {name: "昌乐县", value: 0},
        {name: "潍城区", value: 0},
        {name: "坊子区", value: 0},
        {name: "临朐县", value: 0},
        {name: "安丘市", value: 0},
        {name: "高密市", value: 0},
        {name: "诸城市", value: 0},
        {name: "寒亭区", value: 0},
        {name: "昌邑市", value: 0},
        {name: "寿光市", value: 0}
    ],
    'yuncheng': [
        {name: "盐湖区", value: 0},
        {name: "河津市", value: 0},
        {name: "永济市", value: 0},
        {name: "稷山县", value: 0},
        {name: "新绛县", value: 0},
        {name: "万荣县", value: 0},
        {name: "闻喜县", value: 0},
        {name: "绛县", value: 0},
        {name: "临猗县", value: 0},
        {name: "夏县", value: 0},
        {name: "垣曲县", value: 0},
        {name: "芮城县", value: 0},
        {name: "平陆县", value: 0}
    ]
}
